source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/TuyaInc/TYPublicSpecs.git'

target 'TYModuleManagerCompatKit_Example' do
  pod 'TYModuleManagerCompatKit', :path => '../'

end
